import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
const worker = await readFile(new URL('../cloudflare-worker.js',import.meta.url),'utf8');
const model = worker.slice(worker.indexOf('const CREATOR_PAGE_BLOCK_TYPES ='),worker.indexOf('function creatorPageRowDocument('));
const parser = worker.slice(worker.indexOf('async function requestJson('),worker.indexOf('async function hashPassword('));
const sandbox = vm.createContext({URL,Date,TextEncoder,MAX_JSON_BODY_BYTES:24576,randomBase64Url:()=> 'fixture-123456'});
vm.runInContext(model + parser,sandbox);
const image='data:image/webp;base64,'+'A'.repeat(260000);
const draft={slug:'test-profile',title:'My page',profileImageUrl:'data:image/svg+xml;base64,AAAA',appearance:{backgroundType:'image',backgroundUrl:image,backgroundDim:0,backgroundFit:'contain',backgroundPosition:'top'},blocks:[{id:'hero-fixture',type:'hero',title:'Hi'}]};
const clean=sandbox.normalizeCreatorPageDocument(draft);
assert.equal(clean.appearance.backgroundUrl,image);
assert.equal(clean.appearance.backgroundDim,0);
assert.equal(clean.appearance.backgroundFit,'contain');
assert.equal(clean.profileImageUrl,'');
assert.equal(sandbox.creatorPageAsset('data:text/html;base64,AAAA'),'');
assert.equal(sandbox.creatorPageAsset('data:image/webp;base64,'+'A'.repeat(300000)),'');
const text=JSON.stringify({document:draft,action:'draft'});
const request={headers:{get:()=>String(Buffer.byteLength(text))},text:async()=>text};
await assert.rejects(sandbox.requestJson(request),error=>error.code==='BODY_TOO_LARGE');
assert.equal((await sandbox.requestJson(request,1000000)).document.appearance.backgroundUrl,image);
console.log('PASS: uploaded asset survives normalization, SVG/oversized assets rejected, expanded body limit scoped to creator-page');
